# Generated by Django 5.0.1 on 2024-01-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_units', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('water_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('electricity_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent_payment_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('management_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('other_recurring_bills', models.ManyToManyField(blank=True, related_name='properties', to='core.otherrecurringbill')),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('krapin', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_phone', models.CharField(max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('disbursment_date', models.DateField(blank=True, null=True)),
                ('property', models.ManyToManyField(blank=True, related_name='landlords', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('roles', models.CharField(blank=True, choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'admin')], max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('property', models.ManyToManyField(blank=True, related_name='property_managers', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id_or_name', models.CharField(max_length=50)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupied', models.BooleanField(default=False)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Enter as percentage (e.g., 10.50 for 10.50%)', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('other_recurring_bills', models.ManyToManyField(blank=True, related_name='units', to='core.otherrecurringbill')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='maintenance_images/')),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='core.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='core.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_item', models.CharField(max_length=100)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(max_length=10)),
                ('previous_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='core.property')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='core.unit')),
            ],
        ),
    ]
