# Generated by Django 5.0.1 on 2024-01-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='other_recurring_bills',
        ),
        migrations.RemoveField(
            model_name='property',
            name='other_recurring_bills',
        ),
        migrations.CreateModel(
            name='PropertyOtherRecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertyrecurringbill', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOtherRecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitrecurringbill', to='core.unit')),
            ],
        ),
        migrations.DeleteModel(
            name='OtherRecurringBill',
        ),
    ]
