# Generated by Django 5.0.1 on 2024-01-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_unit_other_recurring_bills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rent_payment_penalty',
        ),
        migrations.AddField(
            model_name='property',
            name='rent_penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_penalty_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_penalty_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=10, null=True),
        ),
    ]
