# Generated by Django 5.0.1 on 2024-02-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_landlord_property'),
        ('property', '0004_alter_unitotherrecurringbill_bill_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='property',
            field=models.ManyToManyField(blank=True, related_name='landlords', to='property.property'),
        ),
    ]
