# Generated by Django 5.0.1 on 2024-02-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_landlord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanager',
            name='roles',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'admin')], default='viewer', max_length=50),
        ),
    ]
