# Generated by Django 5.0.1 on 2024-02-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_unitotherrecurringbill_bill_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='is_variable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='utility_item',
            field=models.CharField(choices=[('Water', 'Water'), ('Electricity', 'Electricity'), ('Garbage', 'Garbage'), ('Security', 'Security'), ('Internet', 'Internet'), ('Cleaning', 'Cleaning'), ('Service', 'Service'), ('Parking', 'Parking')], max_length=100),
        ),
    ]
