# Generated by Django 5.0.1 on 2024-02-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_utilities_is_variable_alter_utilities_utility_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
