# Generated by Django 5.0.1 on 2024-02-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_utilities_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilities',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
