# Generated by Django 5.0.1 on 2024-01-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.unit'),
        ),
    ]
