# Generated by Django 5.0.1 on 2024-02-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_property_alter_tenant_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdeposit',
            name='deposit_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('water', 'Water'), ('electricity', 'Electricity'), ('service_charge', 'Service Charge'), ('other', 'Other')], max_length=50),
        ),
    ]
