# Generated by Django 5.0.1 on 2024-02-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_tenantstatement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantStatement',
        ),
    ]
