# Generated by Django 5.0.1 on 2024-02-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_alter_expense_property_alter_expense_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_name',
            field=models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('garbage', 'Garbage'), ('security', 'Security'), ('internet', 'Internet'), ('cleaning', 'Cleaning'), ('service', 'Service'), ('opening_balance', 'Opening Balance'), ('parking_fee', 'Parking Fee'), ('vat', 'VAT'), ('other', 'Other'), ('rent_deposit', 'Rent Deposit'), ('water_deposit', 'Water Deposit'), ('electricity_deposit', 'Electricity Deposit'), ('contract_charges', 'Contract Charges'), ('other_deposit', 'Other Deposit')], max_length=100),
        ),
    ]
