# Generated by Django 5.0.1 on 2024-02-15 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_alter_invoiceitem_description_and_more'),
        ('tenant', '0005_delete_tenantstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('money_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('money_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_statement', to='financials.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='tenant.tenant')),
            ],
        ),
    ]
