# Generated by Django 5.0.1 on 2024-02-15 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_payment_created_at_payment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantstatement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
