# Generated by Django 5.0.1 on 2024-02-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0009_tenantstatement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantstatement',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_statement', to='financials.invoice'),
        ),
    ]
