# Generated by Django 5.0.1 on 2024-02-15 21:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customuser_alter_landlord_user_and_more'),
        ('financials', '0010_tenantstatement_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='memo',
            new_name='description',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to='core.customuser'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_name',
            field=models.CharField(blank=True, choices=[('water', 'Water'), ('electricity', 'Electricity'), ('garbage', 'Garbage'), ('security', 'Security'), ('internet', 'Internet'), ('cleaning', 'Cleaning'), ('service', 'Service'), ('opening_balance', 'Opening Balance'), ('parking_fee', 'Parking Fee'), ('vat', 'VAT'), ('other', 'Other'), ('rent_deposit', 'Rent Deposit'), ('water_deposit', 'Water Deposit'), ('electricity_deposit', 'Electricity Deposit'), ('contract_charges', 'Contract Charges'), ('other_deposit', 'Other Deposit')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
