# Generated by Django 5.0.1 on 2024-02-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_rename_memo_invoice_description_invoice_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
    ]
