# Generated by Django 5.0.1 on 2024-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_remove_invoice_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item_name',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('water', 'Water'), ('electricity', 'Electricity'), ('garbage', 'Garbage'), ('security', 'Security'), ('internet', 'Internet'), ('cleaning', 'Cleaning'), ('service', 'Service'), ('opening_balance', 'Opening Balance'), ('parking_fee', 'Parking Fee'), ('vat', 'VAT'), ('other', 'Other'), ('rent_deposit', 'Rent Deposit'), ('water_deposit', 'Water Deposit'), ('electricity_deposit', 'Electricity Deposit'), ('contract_charges', 'Contract Charges'), ('other_deposit', 'Other Deposit')], max_length=100, null=True),
        ),
    ]
