# Generated by Django 5.0.1 on 2024-03-12 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0013_alter_invoice_item_name'),
        ('property', '0007_utilities_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='utility',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='property.utilities'),
        ),
    ]
