# Generated by Django 5.0.1 on 2024-03-12 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_invoice_utility'),
        ('property', '0007_utilities_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='utility',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='property.utilities'),
        ),
    ]
